# Generated by Django 3.0.3 on 2020-05-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20200512_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lcappquestion',
            name='disabled',
        ),
    ]
