# Generated by Django 3.0.3 on 2020-05-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_remove_lcappquestion_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcappquestion',
            name='disabled',
            field=models.CharField(blank=True, default=True, max_length=500),
        ),
    ]
