# Generated by Django 3.0.3 on 2020-05-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_lcappquestion_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lcappquestion',
            name='disabled',
        ),
    ]
