# Generated by Django 3.0.3 on 2020-05-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_auto_20200512_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcappquestion',
            name='initial_value',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='lcappquestion',
            name='section',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
