# Generated by Django 3.0.3 on 2020-05-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_auto_20200518_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcappquestion',
            name='settings',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
