# Generated by Django 3.0.3 on 2020-04-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaryrequirement',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
