# Generated by Django 3.0.3 on 2020-04-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0002_documentaryrequirement_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitallc',
            name='drafts_invoice_value',
            field=models.DecimalField(decimal_places=5, default=1.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='digitallc',
            name='exchange_rate_tolerance',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='digitallc',
            name='unit_error_tolerance',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
    ]
