# Generated by Django 3.0.3 on 2020-04-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0003_auto_20200424_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialinvoicerequirement',
            old_name='units_of_measure',
            new_name='unit_of_measure',
        ),
        migrations.RenameField(
            model_name='digitallc',
            old_name='units_of_measure',
            new_name='unit_of_measure',
        ),
    ]
