# Generated by Django 3.0.3 on 2020-04-19 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0003_auto_20200413_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharterPartyBillOfLadingRequirement',
            fields=[
                ('documentaryrequirement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lc.DocumentaryRequirement')),
            ],
            bases=('lc.documentaryrequirement',),
        ),
        migrations.CreateModel(
            name='CommercialInvoiceRequirement',
            fields=[
                ('documentaryrequirement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lc.DocumentaryRequirement')),
                ('invoice_issuer', models.CharField(blank=True, max_length=500, null=True)),
                ('recipient', models.CharField(blank=True, max_length=500, null=True)),
                ('currency', models.CharField(blank=True, max_length=500, null=True)),
                ('goods_description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            bases=('lc.documentaryrequirement',),
        ),
        migrations.CreateModel(
            name='CourierReceiptRequirement',
            fields=[
                ('documentaryrequirement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lc.DocumentaryRequirement')),
            ],
            bases=('lc.documentaryrequirement',),
        ),
        migrations.CreateModel(
            name='InsuranceDocumentRequirement',
            fields=[
                ('documentaryrequirement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lc.DocumentaryRequirement')),
                ('issued_by_insurer', models.BooleanField(default=False)),
                ('all_originals_present', models.BooleanField(default=False)),
                ('is_not_cover_note', models.BooleanField(default=False)),
                ('covered_prior_to_shipment', models.BooleanField(default=False)),
                ('coverage_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            bases=('lc.documentaryrequirement',),
        ),
        migrations.CreateModel(
            name='TransportDocumentRequirement',
            fields=[
                ('documentaryrequirement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lc.DocumentaryRequirement')),
                ('carrier_name', models.CharField(blank=True, max_length=500, null=True)),
                ('signed_by_carrier_agent_or_master', models.BooleanField(default=False)),
            ],
            bases=('lc.documentaryrequirement',),
        ),
        migrations.CreateModel(
            name='AirTransportDocument',
            fields=[
                ('transportdocumentrequirement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lc.TransportDocumentRequirement')),
            ],
            bases=('lc.transportdocumentrequirement',),
        ),
        migrations.CreateModel(
            name='BillOfLadingRequirement',
            fields=[
                ('transportdocumentrequirement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lc.TransportDocumentRequirement')),
            ],
            bases=('lc.transportdocumentrequirement',),
        ),
        migrations.CreateModel(
            name='MultimodalTransportDocumentRequirement',
            fields=[
                ('transportdocumentrequirement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lc.TransportDocumentRequirement')),
                ('charge_location', models.CharField(blank=True, max_length=500, null=True)),
                ('charge_date', models.DateField(blank=True, null=True)),
                ('charge_destination', models.CharField(blank=True, max_length=500, null=True)),
                ('not_subject_to_charter_party', models.BooleanField(default=False)),
            ],
            bases=('lc.transportdocumentrequirement',),
        ),
        migrations.CreateModel(
            name='NonNegotiableSeaWaybillRequirement',
            fields=[
                ('transportdocumentrequirement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lc.TransportDocumentRequirement')),
            ],
            bases=('lc.transportdocumentrequirement',),
        ),
        migrations.CreateModel(
            name='RoadRailInlandWaterwayTransportDocumentsRequirement',
            fields=[
                ('transportdocumentrequirement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lc.TransportDocumentRequirement')),
            ],
            bases=('lc.transportdocumentrequirement',),
        ),
    ]
