# Generated by Django 3.0.3 on 2020-05-04 00:58

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0004_auto_20200424_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialinvoicerequirement',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='commercialinvoicerequirement',
            name='units_purchased',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='digitallc',
            name='drafts_invoice_value',
            field=models.DecimalField(decimal_places=5, default=Decimal('100.00000'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='documentaryrequirement',
            name='for_lc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc.DigitalLC'),
        ),
    ]
