# Generated by Django 3.0.3 on 2020-05-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0005_auto_20200504_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitallc',
            name='applicant_and_ap_j_and_s_obligated',
            field=models.BooleanField(default=False),
        ),
    ]
