# Generated by Django 3.0.3 on 2020-05-25 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('lc', '0006_auto_20200518_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalLCTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(blank=True, default='', max_length=250)),
                ('beneficiary_address', models.CharField(blank=True, default='', max_length=250)),
                ('advising_bank', models.CharField(blank=True, default='', max_length=250)),
                ('forex_contract_num', models.CharField(blank=True, default='', max_length=250)),
                ('exchange_rate_tolerance', models.CharField(blank=True, default='', max_length=250)),
                ('credit_delivery_means', models.CharField(blank=True, default='', max_length=250)),
                ('currency_denomination', models.CharField(blank=True, default='', max_length=5)),
                ('confirmation_means', models.CharField(blank=True, default='', max_length=1000)),
                ('paying_other_banks_fees', models.CharField(blank=True, default='', max_length=100)),
                ('credit_expiry_location', models.CharField(blank=True, default='', max_length=100)),
                ('credit_availability', models.CharField(blank=True, default='', max_length=250)),
                ('paying_acceptance_and_discount_charges', models.CharField(blank=True, default='', max_length=100)),
                ('arranging_own_insurance', models.BooleanField(blank=True, null=True)),
                ('insurance_percentage', models.CharField(blank=True, default='', max_length=500)),
                ('selected_insurance_risks_covered', models.CharField(blank=True, default='', max_length=500)),
                ('other_insurance_risks_covered', models.CharField(blank=True, default='', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessEmployee')),
            ],
            options={
                'unique_together': {('user', 'beneficiary_name')},
            },
        ),
    ]
