# Generated by Django 3.0.3 on 2020-05-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('lc', '0007_digitallctemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitallctemplate',
            name='merch_description',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='digitallctemplate',
            name='purchased_item',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='digitallctemplate',
            name='unit_of_measure',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='digitallctemplate',
            unique_together={('user', 'beneficiary_name', 'purchased_item')},
        ),
    ]
