# Generated by Django 3.0.3 on 2020-05-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0008_auto_20200526_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitallctemplate',
            name='certificate_of_origin',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='digitallctemplate',
            name='inspection_certificate',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='digitallctemplate',
            name='other_draft_accompiants',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='digitallctemplate',
            name='packing_list',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='digitallctemplate',
            name='required_transport_docs',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
