# Generated by Django 3.0.3 on 2020-05-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0011_digitallctemplate_commercial_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitallctemplate',
            name='template_name',
            field=models.CharField(default='Template', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='digitallctemplate',
            unique_together=set(),
        ),
    ]
