# Generated by Django 3.0.3 on 2020-06-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0016_digitallc_cash_secure'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciallyDesignatedNational',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=350)),
                ('type', models.CharField(blank=True, default='', max_length=12)),
                ('program', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('call_sign', models.CharField(blank=True, default='', max_length=8)),
                ('vessel_type', models.CharField(blank=True, default='', max_length=25)),
                ('tonnage', models.CharField(blank=True, default='', max_length=14)),
                ('grt', models.CharField(blank=True, default='', max_length=8)),
                ('vessel_flag', models.CharField(blank=True, default='', max_length=40)),
                ('vessel_owner', models.CharField(blank=True, default='', max_length=150)),
                ('remarks', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SpeciallyDesignatedNationalAlternate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=8)),
                ('name', models.CharField(blank=True, default='', max_length=350)),
                ('remarks', models.CharField(blank=True, default='', max_length=200)),
                ('sdn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc.SpeciallyDesignatedNational')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciallyDesignatedNationalAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=750)),
                ('address_group', models.CharField(blank=True, default='', max_length=116)),
                ('country', models.CharField(blank=True, default='', max_length=250)),
                ('remarks', models.CharField(blank=True, default='', max_length=200)),
                ('sdn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc.SpeciallyDesignatedNational')),
            ],
        ),
    ]
