# Generated by Django 3.0.3 on 2020-06-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0017_speciallydesignatednational_speciallydesignatednationaladdress_speciallydesignatednationalalternate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciallydesignatednational',
            name='call_sign',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='speciallydesignatednational',
            name='grt',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='speciallydesignatednational',
            name='program',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='speciallydesignatednational',
            name='remarks',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='speciallydesignatednational',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='speciallydesignatednational',
            name='tonnage',
            field=models.CharField(blank=True, default=None, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='speciallydesignatednational',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='speciallydesignatednational',
            name='vessel_flag',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='speciallydesignatednational',
            name='vessel_owner',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='speciallydesignatednational',
            name='vessel_type',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='speciallydesignatednationaladdress',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='speciallydesignatednationaladdress',
            name='address_group',
            field=models.CharField(blank=True, default=None, max_length=116, null=True),
        ),
        migrations.AlterField(
            model_name='speciallydesignatednationaladdress',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='speciallydesignatednationaladdress',
            name='remarks',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='speciallydesignatednationalalternate',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='speciallydesignatednationalalternate',
            name='remarks',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='speciallydesignatednationalalternate',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
    ]
