# Generated by Django 3.0.3 on 2020-06-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0018_auto_20200615_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciallydesignatednational',
            name='cleansed_name',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
        migrations.AddField(
            model_name='speciallydesignatednationalalternate',
            name='cleansed_name',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
    ]
