# Generated by Django 3.0.3 on 2020-06-19 22:35

from django.db import migrations, models
import lc.models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0019_auto_20200616_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='lc',
            name='sanction_auto_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='lc',
            name='sanction_bank_approval',
            field=models.CharField(choices=[(lc.models.status['INC'], 'incomplete'), (lc.models.status['ACC'], 'accepted'), (lc.models.status['REJ'], 'rejected')], default=lc.models.status['INC'], max_length=10),
        ),
    ]
