# Generated by Django 3.0.3 on 2020-06-20 23:40

from django.db import migrations, models
import django.db.models.deletion
import lc.models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0020_auto_20200619_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='opac_sanction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('alias', models.CharField(blank=True, max_length=1000, null=True)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lc',
            name='ofac_bank_approval',
            field=models.CharField(choices=[(lc.models.Status['INC'], 'incomplete'), (lc.models.Status['ACC'], 'accepted'), (lc.models.Status['REJ'], 'rejected')], default=lc.models.Status['INC'], max_length=10),
        ),
        migrations.CreateModel(
            name='SDN_LC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lc.LC')),
                ('sdn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lc.SpeciallyDesignatedNational')),
            ],
        ),
    ]
