# Generated by Django 3.0.3 on 2020-06-20 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0020_auto_20200619_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDN_LC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lc.LC')),
                ('sdn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lc.SpeciallyDesignatedNational')),
            ],
        ),
    ]
