# Generated by Django 3.0.3 on 2020-06-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0021_auto_20200620_2340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='opac_sanction',
            new_name='OFACSanction',
        ),
    ]
