# Generated by Django 3.0.3 on 2020-06-20 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0020_auto_20200619_2235'),
        ('lc', '0021_sdn_lc'),
    ]

    operations = [
    ]
