# Generated by Django 3.0.3 on 2020-06-21 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0022_auto_20200620_2345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OFACSanction',
        ),
    ]
