# Generated by Django 3.0.3 on 2020-06-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0023_delete_ofacsanction'),
    ]

    operations = [
        migrations.AddField(
            model_name='lc',
            name='ofac_sanctions',
            field=models.ManyToManyField(to='lc.SpeciallyDesignatedNational'),
        ),
        migrations.DeleteModel(
            name='SDN_LC',
        ),
    ]
