# Generated by Django 3.0.3 on 2020-06-23 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0024_auto_20200621_0040'),
        ('lc', '0022_merge_20200620_2331'),
    ]

    operations = [
    ]
