# Generated by Django 3.0.3 on 2020-06-22 22:53

from django.db import migrations, models
import django.db.models.deletion
import lc.models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0024_auto_20200621_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lc',
            name='ofac_bank_approval',
            field=models.CharField(choices=[(lc.models.Status['INC'], 'incomplete'), (lc.models.Status['ACC'], 'accepted'), (lc.models.Status['REJ'], 'rejected'), (lc.models.Status['REQ'], 'requested')], default=lc.models.Status['INC'], max_length=10),
        ),
        migrations.AlterField(
            model_name='lc',
            name='sanction_bank_approval',
            field=models.CharField(choices=[(lc.models.Status['INC'], 'incomplete'), (lc.models.Status['ACC'], 'accepted'), (lc.models.Status['REJ'], 'rejected'), (lc.models.Status['REQ'], 'requested')], default=lc.models.Status['INC'], max_length=10),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(max_length=20)),
                ('beneficiary_viewable', models.BooleanField(blank=True, default=False)),
                ('lc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc.LC')),
            ],
        ),
    ]
