# Generated by Django 3.0.3 on 2020-06-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0025_merge_20200623_0033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='opac_sanction',
        ),
        migrations.AddField(
            model_name='lc',
            name='import_license_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SDN_LC',
        ),
    ]
