# Generated by Django 3.0.3 on 2020-06-22 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0028_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('message', models.CharField(max_length=500)),
                ('client_viewable', models.BooleanField(blank=True, default=False)),
                ('issuer_viewable', models.BooleanField(blank=True, default=False)),
                ('beneficiary_viewable', models.BooleanField(blank=True, default=False)),
                ('lc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc.LC')),
            ],
        ),
    ]
