# Generated by Django 3.0.3 on 2020-06-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0031_auto_20200623_0020'),
        ('lc', '0027_auto_20200623_0125'),
    ]

    operations = [
    ]
