# Generated by Django 3.0.3 on 2020-06-23 07:31

from django.db import migrations, models
import lc.models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0032_merge_20200623_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lc',
            name='ofac_bank_approval',
            field=models.CharField(choices=[(lc.models.Status['INC'], 'incomplete'), (lc.models.Status['ACC'], 'accepted'), (lc.models.Status['REJ'], 'rejected'), (lc.models.Status['REQ'], 'requested')], default=lc.models.Status['INC'], max_length=10),
        ),
        migrations.AlterField(
            model_name='lc',
            name='sanction_bank_approval',
            field=models.CharField(choices=[(lc.models.Status['INC'], 'incomplete'), (lc.models.Status['ACC'], 'accepted'), (lc.models.Status['REJ'], 'rejected'), (lc.models.Status['REQ'], 'requested')], default=lc.models.Status['INC'], max_length=10),
        ),
    ]
