# Generated by Django 3.0.3 on 2020-06-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0034_auto_20200623_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lc',
            name='import_license_message',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
