# Generated by Django 3.0.3 on 2020-06-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0035_auto_20200623_1520'),
        ('lc', '0034_lc_import_license_approval'),
    ]

    operations = [
    ]
