# Generated by Django 3.0.3 on 2020-06-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0036_lc_boycott_language_status'),
        ('lc', '0036_merge_20200623_1551'),
    ]

    operations = [
    ]
