# Generated by Django 3.0.3 on 2020-06-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0037_merge_20200629_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hts_code', models.CharField(max_length=6, unique=True)),
                ('standard_deviation', models.DecimalField(decimal_places=2, max_digits=19)),
                ('mean', models.DecimalField(decimal_places=2, max_digits=19)),
                ('created_date', models.DateField()),
            ],
        ),
    ]
