# Generated by Django 3.0.3 on 2020-06-30 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0040_digitallc_hts_code'),
        ('lc', '0037_merge_20200629_1723'),
    ]

    operations = [
    ]
