# Generated by Django 3.0.3 on 2020-07-06 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0041_merge_20200702_2206'),
        ('lc', '0041_merge_20200630_0251'),
    ]

    operations = [
    ]
