# Generated by Django 3.0.3 on 2020-07-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0041_merge_20200630_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitallctemplate',
            name='hts_code',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
