# Generated by Django 3.0.3 on 2020-07-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0042_merge_20200706_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitallc',
            name='cash_secure',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=17, null=True),
        ),
    ]
