# Generated by Django 3.0.3 on 2020-07-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0042_digitallctemplate_hts_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitallctemplate',
            name='beneficiary_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
