# Generated by Django 3.0.3 on 2020-07-09 13:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0043_auto_20200708_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitallc',
            name='drafts_invoice_value',
            field=models.DecimalField(blank=True, decimal_places=5, default=Decimal('100.00000'), max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='digitallc',
            name='other_data',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
