# Generated by Django 3.0.3 on 2020-07-10 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0043_digitallctemplate_beneficiary_country'),
        ('lc', '0044_auto_20200709_1340'),
    ]

    operations = [
    ]
