# Generated by Django 3.0.3 on 2020-07-15 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0046_digitallctemplate_beneficiary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitallctemplate',
            name='beneficiary_address',
        ),
        migrations.RemoveField(
            model_name='digitallctemplate',
            name='beneficiary_country',
        ),
        migrations.RemoveField(
            model_name='digitallctemplate',
            name='beneficiary_name',
        ),
    ]
