# Generated by Django 3.0.3 on 2020-07-24 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0020_auto_20200716_1636'),
        ('lc', '0047_auto_20200715_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='lc',
            name='type_3_advising_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lc_lc_type_3_advising_bank', to='bank.Bank'),
        ),
    ]
