# Generated by Django 3.0.3 on 2020-07-23 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0020_auto_20200716_1636'),
        ('lc', '0050_auto_20200723_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lc',
            name='advising_type',
        ),
        migrations.AddField(
            model_name='lc',
            name='type_3_advising_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lc_lc_type_3_advising_bank', to='bank.Bank'),
        ),
        migrations.AlterField(
            model_name='digitallc',
            name='confirmation_means',
            field=models.CharField(default='No Confirmation', max_length=1000),
        ),
    ]
