# Generated by Django 3.0.3 on 2020-07-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0048_lc_type_3_advising_bank'),
        ('lc', '0051_auto_20200723_2034'),
    ]

    operations = [
    ]
