# Generated by Django 3.0.3 on 2020-07-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0052_merge_20200726_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='lc',
            name='beneficiary_selected_doc_req',
            field=models.BooleanField(default=False),
        ),
    ]
