# Generated by Django 3.0.3 on 2020-08-11 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0020_auto_20200716_1636'),
        ('lc', '0053_lc_beneficiary_selected_doc_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='lc',
            name='issuer_can_select_bene_advisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lc',
            name='issuer_selected_advising_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lc_lc_issuer_selected_advising_bank', to='bank.Bank'),
        ),
        migrations.AddField(
            model_name='lc',
            name='issuer_selected_doc_req',
            field=models.BooleanField(default=False),
        ),
    ]
