# Generated by Django 3.0.3 on 2020-08-14 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0054_auto_20200811_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lc',
            name='issuer_selected_doc_req',
        ),
    ]
