# Generated by Django 3.0.3 on 2020-06-05 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_lcappquestion_settings'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_credit_amt', models.DecimalField(decimal_places=2, default=240000, max_digits=20)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Bank')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
            ],
            options={
                'unique_together': {('bank', 'business')},
            },
        ),
    ]
