# Generated by Django 3.0.3 on 2020-06-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_lcappquestion_settings'),
        ('business', '0002_approvedcredit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='approved_credit',
        ),
        migrations.AddField(
            model_name='business',
            name='approved_credit',
            field=models.ManyToManyField(through='business.ApprovedCredit', to='bank.Bank'),
        ),
    ]
