# Generated by Django 3.0.3 on 2020-06-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20200605_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='approvedcredit',
            name='approved_credit_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='annual_cashflow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='balance_available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
