# Generated by Django 3.0.3 on 2020-06-30 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_lcappquestion_settings'),
        ('business', '0007_auto_20200630_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizedbanks',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Bank'),
        ),
    ]
