# Generated by Django 3.0.3 on 2020-07-09 03:37

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20200630_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizedbanks',
            name='status',
            field=models.CharField(choices=[(business.models.AuthStatus['AUTH'], 'Authorized'), (business.models.AuthStatus['UNAUTH'], 'Unauthorized')], default=business.models.AuthStatus['UNAUTH'], max_length=20),
        ),
    ]
